name: Upload work-book_backend Staging Package

on:
  push:
    branches: [main, dev]

jobs:
  build-and-package:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
            java-version: 17
            distribution: 'temurin'
            architecture: x64

      - name: Build with Maven Wrapper
        run: ./mvnw package

      - name: Package the Artifact
        run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v3
        with:
          name: word-book_backend
          path: staging



