name: Code Test

on:
  pull_request:
    branches: [main, dev]

jobs:
  build-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
            java-version: 17
            distribution: 'temurin'
            architecture: x64

      - name: Validate Project with Maven Wrapper
        run: ./mvnw validate

      - name: Compile with Maven Wrapper
        run: ./mvnw clean compile

      - name: Run Unit Tests with Maven Wrapper
        run: ./mvnw test

      - name: Run Integration Tests with Maven Wrapper
        run: ./mvnw verify